name: Run R Script Daily

on:
  # Jadwal otomatis
  schedule:
    - cron: '0 23 * * *'  # 23:00 UTC = 06:00 WIB
  
  # Trigger manual untuk testing
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4
      
      # Setup R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'
      
      # Install dependencies (jika ada)
      - name: Install R packages
        run: |
          install.packages(c("httr", "jsonlite", "dplyr", "quantmod", "rugarch", "TTR", "jsonlite", "httr2", 
                       "lubridate", "dplyr"))
        shell: Rscript {0}
      
      # Jalankan script
      - name: Run R script
        run: Rscript eod.R
